### ISSUE TITLE
Youtube Player fullScreen button does not work when its played in WebView

### ISSUE THREAD

**Issue by Vaibhav2002** [KevinnZou/compose-webview-multiplatform#168]
If I load a Youtube iFrame in this WebView, the fullscreen button does not make the video fullScreen
This only happens in Android.
On iOS FullScreen button makes the Video fullscreen and also supports screen rotation

Source Code:
```kotlin
val webViewState = rememberWebViewStateWithHTMLData(embed.html)
val navigator = rememberWebViewNavigator()
val bgColor = MaterialTheme.colorScheme.surface
DisposableEffect(Unit) {
    webViewState.webSettings.apply {
        isJavaScriptEnabled = true
        supportZoom = false
        backgroundColor = bgColor
        iOSWebSettings.apply {
            showVerticalScrollIndicator = false
            showHorizontalScrollIndicator = false
            scrollEnabled = false
        }
        androidWebSettings.apply {
            safeBrowsingEnabled = true
        }
    }
    onDispose { }
}
WebView(
    state = webViewState,
    modifier = modifier.height(400.dp),
    navigator = navigator,
    captureBackPresses = false
)
```

**Comment by Vaibhav2002** [comment]
Maybe these methods of the `WebChromeClient` needs to be overriden
```kotlin
override fun onShowCustomView(view: View, callback: CustomViewCallback) {
  super.onShowCustomView(view, callback)
}

override fun onHideCustomView() {
  super.onHideCustomView()
}
```

**Comment by KevinnZou** [comment]
@Vaibhav2002 Thanks for your feedback! Yes, this requires us to override the `onShowCustomView` and handle the full-screen logic inside. This further requires us to support the custom`WebChromeClient`. However, I am sorry that we are not planning to provide this feature currently since it can be complex to implement it in the multiplatform context. 

You are welcome to submit a PR for it or directly fork this lib and define your own logic in it.
