### ISSUE TITLE
html not showing in ios

### ISSUE THREAD

**Issue by husorpandiangan9** [KevinnZou/compose-webview-multiplatform#189]
<img width="729" alt="Screenshot 2024-07-04 at 11 52 50" src="https://github.com/KevinnZou/compose-webview-multiplatform/assets/141312679/af7ab581-94e9-464b-a457-c1d84a12d7fc">

<img width="630" alt="Screenshot 2024-07-04 at 11 53 58" src="https://github.com/KevinnZou/compose-webview-multiplatform/assets/141312679/c30668b6-1f29-450e-b3ab-987cc10a279b">

i use kotlin 2.0 and compose 1.6.10

**Comment by husorpandiangan9** [comment]
any ide for this ?

**Comment by KevinnZou** [comment]
@husorpandiangan9 It appears to be caused by the size issue. Please consider removing the picture above or adding the fillMaxSize modifier to the WebView component to test whether it works under full-screen mode.

**Comment by husorpandiangan9** [comment]
Cool, its work when adding fillMaxSize. Thanks @KevinnZou 

> @husorpandiangan9 It appears to be caused by the size issue. Please consider removing the picture above or adding the fillMaxSize modifier to the WebView component to test whether it works under full-screen mode.

**Comment by MobiDevelop** [comment]
I found this issue when embedding the WebView into a scrollable container. This works fine on Android but on iOS the underlying WebView has no size, and therefore shows as blank. Is there a plan to support this or do we need to resort to other means to determine a fixed size to give the WebView?

**Comment by KevinnZou** [comment]
@MobiDevelop Did you try with fillMaxSize? If it does not work, then it is the issue with CMP and we may not have the solution to fix it. I am so sorry for that.

**Comment by MobiDevelop** [comment]
@KevinnZou I did, but since it was in a column having `verticalScroll()` the height doesn't grow. I've had some luck with giving the WebView a `heightIn` with a suitable `min`, then observing the content height of the web content and resizing the UIKitView to match.

In my case, I am interested in presenting the web content as part of my main scrolling content without its own scrolling (but has to remain interactive). Unfortunately, in current Compose Multiplatform the touches starting on the embedded view get swallowed and prevent scrolling the outer container - but this looks to be addressed (🤞) in the upcoming 1.7.0 based on commit logs.
