### ISSUE TITLE
Camera issue in webview iOS

### ISSUE THREAD

**Issue by ssvaghasiya** [KevinnZou/compose-webview-multiplatform#21]
Any solution for below issue?

https://github.com/JetBrains/compose-multiplatform/issues/3791

**Comment by KevinnZou** [comment]
Hi, could you provide the test URL?

**Comment by KevinnZou** [comment]
I think Elijah has given an explanation in this reply https://github.com/JetBrains/compose-multiplatform/issues/3791#issuecomment-1753038883

In general, the behavior is intentional rather than a bug. To keep the WebView instance when returning from the camera, you should present a `UIViewController` containing the WebView. An example demonstrating this was also provided. Below is the core part of the example:
```
val navigationController = UINavigationController(rootViewController = ComposeUIViewController {
                NativeNavigationPage()
            })

viewController.presentViewController(navigationController, true, null)
```
You can replace `NativeNavigationPage` with WebView and it should work.  If that doesn't work, I suggest you continue to discuss the issue with Elijah, as it is typically a problem with Compose Multiplatform but WebView.
