### ISSUE TITLE
Media Permission Support

### ISSUE THREAD

**Issue by savan-ixfi** [KevinnZou/compose-webview-multiplatform#4]
Please add media selection support using permission

**Comment by KevinnZou** [comment]
Hi, thanks for your suggestion. However, could you please provide a more detailed explanation of your requirements?

**Comment by savan-ixfi** [comment]
> Hi, thanks for your suggestion. However, could you please provide a more detailed explanation of your requirements?

for example image uploading from device

**Comment by savan-ixfi** [comment]
> > Hi, thanks for your suggestion. However, could you please provide a more detailed explanation of your requirements?
> 
> for example image uploading from device

And also capture image using camera and upload

**Comment by savan-ixfi** [comment]
<img width="288" alt="image" src="https://github.com/KevinnZou/compose-webview-multiplatform/assets/131661149/81c56674-8941-4901-9a36-a632fdb381f4">

for this type of requirements from webview

**Comment by KevinnZou** [comment]
> <img alt="image" width="288" src="https://user-images.githubusercontent.com/131661149/269493709-81c56674-8941-4901-9a36-a632fdb381f4.png">
> for this type of requirements from webview

Could you please share the URL of the aforementioned page for testing purposes? Additionally, have you exclusively tested it on the Android platform? In my experience, when a web page requires access to user media within a mobile application, it typically requires the use of a JSBridge to delegate the request to the native application, rather than handling it solely with JavaScript code.

**Comment by savan-ixfi** [comment]
> > <img alt="image" width="288" src="https://user-images.githubusercontent.com/131661149/269493709-81c56674-8941-4901-9a36-a632fdb381f4.png">
> > for this type of requirements from webview
> 
> Could you please share the URL of the aforementioned page for testing purposes? Additionally, have you exclusively tested it on the Android platform? In my experience, when a web page requires access to user media within a mobile application, it typically requires the use of a JSBridge to delegate the request to the native application, rather than handling it solely with JavaScript code.

Use below url for testing :
https://www.remove.bg/upload

**Comment by savan-ixfi** [comment]
> > > <img alt="image" width="288" src="https://user-images.githubusercontent.com/131661149/269493709-81c56674-8941-4901-9a36-a632fdb381f4.png">
> > > for this type of requirements from webview
> > 
> > 
> > Could you please share the URL of the aforementioned page for testing purposes? Additionally, have you exclusively tested it on the Android platform? In my experience, when a web page requires access to user media within a mobile application, it typically requires the use of a JSBridge to delegate the request to the native application, rather than handling it solely with JavaScript code.
> 
> Use below url for testing : https://www.remove.bg/upload

if possible please reply soon with solution

**Comment by KevinnZou** [comment]
Hello, I have conducted a test on the provided URL. While it functions properly on the desktop platform, it encounters failures on both Android and iOS platforms. This outcome is to be expected as the web page within the mobile application lacks the necessary permissions to access mobile media and file information. Consequently, for tasks involving files or media, it is advisable to implement them natively rather than relying solely on web solutions. Although it is technically feasible to achieve these tasks through web development, the complexity increases significantly. As previously mentioned, it is essential to establish a JSBridge to delegate requests to the native application. Alternatively, a more straightforward approach would involve utilizing a third-party Kotlin Multiplatform library that streamlines the entire process. Please let me know if you have any further questions.

**Comment by savan-ixfi** [comment]
> Hello, I have conducted a test on the provided URL. While it functions properly on the desktop platform, it encounters failures on both Android and iOS platforms. This outcome is to be expected as the web page within the mobile application lacks the necessary permissions to access mobile media and file information.
> 
> Consequently, for tasks involving files or media, it is advisable to implement them natively rather than relying solely on web solutions. Although it is technically feasible to achieve these tasks through web development, the complexity increases significantly. As previously mentioned, it is essential to establish a JSBridge to delegate requests to the native application.
> 
> Alternatively, a more straightforward approach would involve utilizing a third-party Kotlin Multiplatform library that streamlines the entire process. Please let me know if you have any further questions.

if you have any reference or resources please share here

**Comment by KevinnZou** [comment]
> > Hello, I have conducted a test on the provided URL. While it functions properly on the desktop platform, it encounters failures on both Android and iOS platforms. This outcome is to be expected as the web page within the mobile application lacks the necessary permissions to access mobile media and file information.
> > Consequently, for tasks involving files or media, it is advisable to implement them natively rather than relying solely on web solutions. Although it is technically feasible to achieve these tasks through web development, the complexity increases significantly. As previously mentioned, it is essential to establish a JSBridge to delegate requests to the native application.
> > Alternatively, a more straightforward approach would involve utilizing a third-party Kotlin Multiplatform library that streamlines the entire process. Please let me know if you have any further questions.
> 
> if you have any reference or resources please share here

I made a quick search on GitHub and found this repo that may meet your requirements.
https://github.com/Wavesonics/compose-multiplatform-file-picker

**Comment by savan-ixfi** [comment]
> > > Hello, I have conducted a test on the provided URL. While it functions properly on the desktop platform, it encounters failures on both Android and iOS platforms. This outcome is to be expected as the web page within the mobile application lacks the necessary permissions to access mobile media and file information.
> > > Consequently, for tasks involving files or media, it is advisable to implement them natively rather than relying solely on web solutions. Although it is technically feasible to achieve these tasks through web development, the complexity increases significantly. As previously mentioned, it is essential to establish a JSBridge to delegate requests to the native application.
> > > Alternatively, a more straightforward approach would involve utilizing a third-party Kotlin Multiplatform library that streamlines the entire process. Please let me know if you have any further questions.
> > 
> > 
> > if you have any reference or resources please share here
> 
> I made a quick search on GitHub and found this repo that may meet your requirements. https://github.com/Wavesonics/compose-multiplatform-file-picker

if possible i request you to make another repo or provide detailed solution of this requirement with example

**Comment by KevinnZou** [comment]
Hi, I think the repo I provided above already provided a detailed example. Since this requirement is unrelated to my project, I am afraid that I cannot fulfill your requirement. Thanks for your understanding. I would recommend you have a try with the repo provided above first and submit the issue to that repo if you have further questions related to file uploading.
